### ISSUE TITLE
could not find module `ember-get-config` imported from `tiny/admin/newsletter/controller`

### ISSUE THREAD

**Issue by GCorbel** [null-null-null/ember-get-config#1]
Hi,

I simply have this line : 

    import config from 'ember-get-config';

And it throw : 

    could not find module `ember-get-config` imported from `tiny/admin/newsletter/controller`

I'm using Ember 2.4.

**Comment by null-null-null** [comment]
@GCorbel Sorry about the late reply; this email got buried last month. Anyway, I just updated the addon to use the latest Ember version, and it passes all test scenarios (from 1.13.0 through to canary). Try updating and let me know if it fixes the problem!

**Comment by null-null-null** [comment]
Closing for now. Let me know if there's anything else, @GCorbel!

**Comment by bugduino** [comment]
Hi,
I have the same problem when developing an addon using Ember 2.6 .

**Comment by null-null-null** [comment]
First possible cause: is `ember-get-config` in the package.json `devDependencies` or `dependencies`?

**Comment by bugduino** [comment]
It is in `dependencies`. The issue I found is linked with #6

**Comment by null-null-null** [comment]
That's good to hear. We do have a solution, just got to get it merged. I'll update here once it's in.
