### ISSUE TITLE
Shouldn't recommend calling `included`.

### ISSUE THREAD

**Issue by nathanhammond** [null-null-null/ember-get-config#10]
From your README, recommending this is a bad idea:

```javascript
included: function(app) {
  while (app.app) {
    app = app.app;
  }

  this.eachAddonInvoke('included', [app]);

  this._super.included.apply(this, [app]);
}
```

I'm unsure why you have to do this? If your own addon depends on ember-get-config, ember-get-config must simply export in its treeForAddon the file you're writing at the file path `/modules/ember-get-config`.

This will make it available to _all_ addons if it is included by just one, and it will also ensure it gets clobbered if multiple addons include it so you only end up with one instance in the output.

Would you mind reworking this to ensure safety?

**Comment by null-null-null** [comment]
I would love to find a way to do this. Right now, I'm using the `included` hook instead of the `treeForAddon` hook because of [this line](https://github.com/null-null-null/ember-get-config/blob/master/index.js#L17). That is, I need the `app.project.config` that `included` passes, which I don't have access to with `treeForAddon`.

Let me know if I'm misunderstanding your suggestion or if there's some other way you can think of approaching this. I'd appreciate your insights here.

**Comment by nathanhammond** [comment]
```javascript
function findRoot(current) {
  var app;

  // Keep iterating upward until we don't have a grandparent.
  // Has to do this grandparent check because at some point we hit the project.
  do {
    app = current.app || app;
  } while (current.parent && current.parent.parent && (current = current.parent));

  return app;
}

anyHookYouWant() {
  var root = findRoot(this);
  root.project.config(process.env.EMBER_ENV)['modulePrefix'];
}
```

**Comment by null-null-null** [comment]
Thanks @nathanhammond, that did the trick. `v0.1.8`

**Comment by nathanhammond** [comment]
Thank you for taking the time to get this updated!

Can you do me _one_ more favor? Since this previously recommended a second invocation of the `included` hook can you add a warning into the `included` hook of this addon if it is invoked twice, asking them to remove the previously recommended approach?

Something like:
```javascript
var count = 0;
module.exports = {
  included: function() {
    count++;
    if (count > 1) {
      findRoot(this).project.ui.writeDeprecateLine('ember-get-config previously recommended to reinvoke the included hook. That is on longer recommended. Please remove the additional invocation.');
    }
  }
};
```

(Not a PR because coding on GitHub.)

**Comment by null-null-null** [comment]
No worries. The deprecation is now in `v0.1.9` Thanks again for helping with this.

**Comment by nathanhammond** [comment]
Thank you so much! I think you're closing in on a 1.0.0 😄
