### ISSUE TITLE
Deprecation warning in Ember 2.10.0

### ISSUE THREAD

**Issue by denzo** [null-null-null/ember-get-config#11]
`Ember 2.10.0`

```
DEPRECATION: `ember-get-config` previously recommended reinvoking the `included` hook, but that is no longer recommended. Please remove the additional invocation.
```

**Comment by null-null-null** [comment]
We're throwing that deprecation since you no longer need to manually invoke the included hook in your addon. You can get rid of the deprecation by removing that invocation. For instance, you might have something like this:

```js
included: function(app) {
  while (app.app) {
    app = app.app;
  }

  this.eachAddonInvoke('included', [app]);

  this._super.included.apply(this, [app]);
}
```

This was previously recommended in the readme, but it's no longer necessary and can even cause problems. Unless you're using it for other reasons, you can simply delete it now.

**Comment by dfreeman** [comment]
I think this is actually a side effect of how this addon is counting inclusions in combination with how recent versions of npm and Yarn deduplicate dependencies. If my app uses more than one addon that depends on ember-get-config, with npm 2 the actual installed modules would (usually) reflect the dependency structure:

```
my-app
├── addon-a
│   └── ember-get-config
└── addon-b
    └── ember-get-config
```

With npm 3/4 and Yarn, however, ember-get-config would be deduped and hoisted, resulting in:


```
my-app
├── addon-a
├── addon-b
└── ember-get-config
```

This means there'd only be one copy of ember-get-config, but it still gets `included()` twice, once for each addon that depends on it, incrementing [this variable](https://github.com/null-null-null/ember-get-config/blob/master/index.js#L6) each time.

**Comment by dfreeman** [comment]
@denzo I think this should be fixed in 0.2.0 — can you confirm?

**Comment by denzo** [comment]
@dfreeman yes, works like charm! Thanks

**Comment by null-null-null** [comment]
Thanks again, @dfreeman and @denzo.
