### ISSUE TITLE
cannot find module with ember-cli v2.12.0-beta.1

### ISSUE THREAD

**Issue by davidpett** [null-null-null/ember-get-config#14]
I have forked and updated to the latest cli release: https://github.com/davidpett/ember-get-config

```
Uncaught Error: Could not find module `ember-get-config` imported from `dummy/controllers/application`
    at missingModule (loader.js:239)
    at findModule (loader.js:250)
    at Module.findDeps (loader.js:190)
    at findModule (loader.js:253)
    at requireModule (loader.js:20)
    at Class._extractDefaultExport (resolver.js:382)
    at Class.resolveOther (resolver.js:79)
    at Class.superWrapper [as resolveOther] (ember.debug.js:40426)
    at Class.resolveController (ember.debug.js:5177)
    at Class.resolve (ember.debug.js:5032)
```
is the error that I get. If you have any insight, please comment and I can continue to dig and see if I can find the cause of the issue.

**Comment by null-null-null** [comment]
Thanks for the heads up, @davidpett. I'll look into this as soon as I get a solid block of time.

**Comment by null-null-null** [comment]
@davidpett I'm not sure what's going on, but I did stumble on a quick fix while debugging the issue: simply include a blank `addon/index.js` file. This is the file that `ember-get-config` generates in its top-level `index.js`, and for some reason, it's not being generated by Ember CLI beta when there is no `addon/index.js` file already present. However, when that file is present, Ember CLI generates the correct file. For the time being, `v0.2.1` should fix the problem. On your own branch, you can also just add a blank `addon.index.js` file.

**Comment by davidpett** [comment]
awesome, thanks @null-null-null
