### ISSUE TITLE
Doesn't work with engines

### ISSUE THREAD

**Issue by mydea** [null-null-null/ember-get-config#6]
Hi,

I have been a happy user of ember-get-config for a while now. I am now working on a new app based on engines, and in the process I found out that ember-get-config doesn't work there.

After looking into it, I found out it is because there are now multiple modules that match `const CONFIG_REGEX = /^[^/]+\/config\/environment$/;`, because the engines also have their own configs.
I ended up using an adaption of your code with a more specific regex (e.g. `my-app/config/environment`). I am not quite sure how this could be generalized , but it would be very neat to be able to do this.

**Comment by null-null-null** [comment]
Thanks for reporting this. Along with @BrianSipple, I've been exploring possible ways to grab the config in the `index.js` include hook. Since `ember-get-config` was working well enough, I wasn't taking those explorations very seriously, but this gives me reason to reconsider this approach.

**Comment by null-null-null** [comment]
@mydea This may be fixed with `0.1.0`. Would you mind confirming?

**Comment by mydea** [comment]
It works fine now for me - thanks! (tested in 0.1.3)

**Comment by null-null-null** [comment]
Good to hear!
