### ISSUE TITLE
[question] config duplication

### ISSUE THREAD

**Issue by Sinled** [null-null-null/ember-get-config#8]
Thanks for addon, it is very handy, 

but i have small question

Am i missing something or addon duplicates config file 
https://github.com/null-null-null/ember-get-config/blob/master/index.js#L17 ?
in my case this is additional ~15kb of data.

**Comment by null-null-null** [comment]
If you're not using engines, then it'd be safe to downgrade to `0.0.4`, which won't duplicate the config. I'll also be talking with some people on Friday about an RFC for this problem. `ember-get-config` is convenient, but it's also a hack and that's becoming more apparent with the advent of engines. I'd like to see the community devise a real solution to this.

**Comment by null-null-null** [comment]
@Sinled Just released a `v0.1.4` that should both avoid duplication and work a little better with engines. It's still not an ideal solution, but there's an RFC on the way for something better.
