### ISSUE TITLE
BLOCKER! Issue started from yesterday

### ISSUE THREAD

**Issue by Blackening999** [null-null-null/ember-get-config#9]
loader.js:219 Uncaught Error: Could not find module `dummy/config/environment` imported from `ember-get-config/index`

I've started seeing this error after updating bower/npm. Seems like some upgrade spoiled the party

This might be not appropriate to write about it here, cause it's freaking out in 
https://github.com/ciena-blueplanet/ember-prop-types/issues/39

Still no help from error message :\

**Comment by null-null-null** [comment]
Should be fixed now. Let me know if this comes back!
